name = "Ivy"
license = "Unlicense"
licenselink = "https://github.com/yihui/hugo-ivy/blob/master/LICENSE.md"
description = "A theme ported from Ivy"
homepage = "https://misscutee.com"
tags = ["minimal", "blog", "personal", "clean", "simple", "minimalist"]
features = ["blog"]
min_version = "0.18"

[author]
  name = "Misscutee"
  homepage = "https://misscutee.com"

[original]
    author = "dmulholland"
    homepage = "http://mulholland.xyz/docs/ivy/"
    repo = "https://github.com/dmulholland/ivy"
